// import '!style-loader!css-loader!normalize.css';
// import '!style-loader!css-loader!bootstrap/dist/css/bootstrap.css'
import '!style-loader!css-loader!animate.css/animate.css'
import '!style-loader!css-loader!hover.css/css/hover.css'
// import '!style-loader!css-loader!intro.js/introjs.css'
import '!style-loader!css-loader!nprogress/nprogress.css'
import '!style-loader!css-loader!sweetalert/dist/sweetalert.css'
// import '!style-loader!css-loader!dragula/dist/dragula.css'
import '!style-loader!css-loader!./font-awesome.css'
import '!style-loader!css-loader!./common.css'
