// import '!style-loader!css-loader!normalize.css';
// import '!style-loader!css-loader!bootstrap/dist/css/bootstrap.css'
import 'animate.css/animate.css'
import 'hover.css/css/hover.css'
import 'nprogress/nprogress.css'
import 'sweetalert/dist/sweetalert.css'
// import 'dragula/dist/dragula.css'
// import '!style-loader!css-loader!intro.js/introjs.css'
import './font-awesome.css'
import './common.css'
